version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/site"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/draw"
    schedule:
      interval: "weekly"
